pipeline
{
    options
    {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }
    agent any

    stages
    {
        stage('SCM: code update')
        {
            steps
            {
                checkout([
                        $class: 'GitSCM', branches: [[name: 'master']],
                        userRemoteConfigs: [[url: 'https://github.com/tikalk/pipelineForceCode.git' ,credentialsId:'']]
                ])
            }
        }
        stage('Run selected tests')
        {
            steps
            {
                script
                {
                    docker.image("python:2.7-wheezy").inside('-u root')
                    {
                        sh "pip install pytest"
                        sh "mkdir -p allure-results"
                        sh "mkdir -p junit-results"
                        sh "py.test --alluredir=allure-results --junitxml=.unit-results/TESTS.xml python/test -v"
                    }
                }
            }
        }
    }
    post
    {
        always
        {
            junit 'junit-results/TESTS.xml'
            allure(commandline: '2.5.0', includeProperties: false, jdk: '', properties: [[key: 'httpallure.tests.management.pattern', value: 'http://tms.company.com/%s']], results: [[path: './allure-results']])
        }
    }
}
