pipeline
{
    options
    {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }
    agent any

    stages
    {
        stage('SCM: code update')
        {
            steps
            {
                checkout([
                        $class: 'GitSCM', branches: [[name: 'master']],
                        userRemoteConfigs: [[url: 'https://github.com/tikalk/pipelineForceCode.git' ,credentialsId:'']]
                ])
            }
        }
        stage('Run selected tests')
        {
            steps
            {
                script
                {
                    docker.image("python:2.7-wheezy").inside('-u root')
                    {
                        sh "pip install pytest"
                        sh "py.test python/test -v"
                    }
                }
            }
        }
    }
}
