@Library("tikal-pipelib") _

pipeline
{
    options
    {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }
    agent any

    stages
    {
        stage('SCM: code update')
        {
            steps
            {
                checkout([
                        $class: 'GitSCM', branches: [[name: 'master']],
                        userRemoteConfigs: [[url: 'https://github.com/tikalk/pipelineForceCode.git' ,credentialsId:'']]
                ])
            }
        }
        stage('Run all tests')
        {
            steps
            {
                script
                {
                    docker.image("python:2.7-wheezy").inside('-u root')
                    {
                        sh "pip install pytest pytest-dependency pytest-allure-adaptor"
                        sh "mkdir -p allure-results"
                        sh "mkdir -p junit-results"
                        try
                        {
                            sh "py.test --alluredir=allure-results --junitxml=junit-results/TESTS.xml python/test -v"
                        }
                        catch(error)
                        {
                        }
                    }
                }
            }
        }
    }
    post
    {
        always
        {
            junit 'junit-results/TESTS.xml'
            allure(commandline: '2.5.0',
                    includeProperties: false, jdk: '',
                    properties: [[key: 'httpallure.tests.management.pattern',
                                  value: 'http://tms.company.com/%s']],
                                  results: [[path: './allure-results']])
            tplGetTestSummary()
        }
    }
}
