@Library("tikal-pipelib") _

pipeline
{
    agent any
    stages
    {
        stage('TEST')
        {
            steps
            {
                echo "Testing Advanced Slack Notification"
            }
        }
    }
    post
    {
        success
        {
            tplAdvancedSlackNotification('SUCCESS',"jenkins-notifications")
        }

        failure
        {
            tplAdvancedSlackNotification('FAILURE',"jenkins-notifications")
        }

        unstable
        {
            tplAdvancedSlackNotification('UNSTABLE',"jenkins-notifications")
        }
    }
}
