@Library ("tikal-pipelib") _

pipeline
{
    agent any

    stages
    {
        stage('Keep build forever')
        {
            steps
            {
                tplKeepBuildForever()
            }
        }
    }
}

