@Library ("tci-library") _

pipeline {
    agent { label 'tci-jnlp-node' }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
        ansiColor('xterm')
        skipDefaultCheckout()
    }
    stages {
        stage("test") {
            steps {
                script {
                    tciGit.gitCheckout(repoUrl: "git@github.com:TikalCI/tci-master.git",
                            dir: 'tci-master',
                            branch: 'test')
                    sh "cat tci-master/test/test.txt > /dev/null"
                    String changes = tciGit.getChangesList()
                    echo "Git changes: ${changes}"
//                    String changers = tciGit.getChangersList()
//                    echo "[Git changers]\n\t${changers}"
                }
            }
        }
    }
}
