@Library ("tci-library") _

pipeline {
    agent { label 'docker-slave' }
    stages {
        stage("test") {
            steps {
                script {
                    tplEcho "test tciGeneral.deprecatedMessage"
                    tciGeneral.timedEcho "test tciGeneral.timedEcho"
                    tciGeneral.setStatusByLogText("Text that will probably won't be in the log")
                }
            }
        }
    }
}
