@Library ("tci-library") _

pipeline {
    agent { label 'tci-jnlp-node' }
    stages {
        stage("test") {
            steps {
                script {
                    tciGeneral.clearWorkspaceAsRoot
                    tplEcho "test tciGeneral.deprecatedMessage"
                    tciGeneral.timedEcho "test tciGeneral.timedEcho"
                    tciGeneral.setStatusByLogText("Text that will probably won't be in the log")
                    boolean found = tciGeneral.findStringInBuildLog("timedEcho")
                    tciGeneral.timedEcho "setStatusByLogText returned ${found}"
                }
            }
        }
    }
}
