@Library ("tci-library") _

pipeline {
    agent none
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
        ansiColor('xterm')
        skipDefaultCheckout()
    }
    stages {
        stage("test") {
            steps {
                script {
                    tciJobs.setRandomBuildStatus ()
                }
            }
        }
    }
}
