pipeline
{
    agent any
    environment
    {
        MAX=4
    }
    stages
    {
        stage('Explore bug')
        {
            steps
            {
                script
                {
                    maxIndex=MAX
                    def loopers = [:]
                    for (int loopIndex = 0; loopIndex < maxIndex; loopIndex++)
                    {
                        loopers["loop-${loopIndex}"] =
                        {
                            echo "loopIndex=${loopIndex}"
                        }
                    }
                    parallel loopers
                }
            }
        }
        stage('Bug workaround')
        {
            steps
            {
                script
                {
                    maxIndex=MAX
                    def loopers = [:]
                    for (int loopIndex = 0; loopIndex < maxIndex; loopIndex++)
                    {
                        index=loopIndex
                        loopers["loop-${index}"] =
                        {
                            echo "index=${index}"
                        }
                    }
                    parallel loopers
                }
            }
        }
    }
}
