@Library ("tci-library") _

pipeline {
    agent { label 'tci-jnlp-node' }
    stages {
        stage("test") {
            steps {
                script {
                    echo "TODO: find a way to test the 'jobs' steps"
                }
            }
        }
    }
}
