@Library ("tikal-pipelib") _

pipeline
{
    parameters
    {
        string(name: 'TEXT', defaultValue: 'Test TEXT', description: 'Enter text to display')
    }

    agent any

    stages
    {
        stage('Display text')
        {
            steps
            {
                tplEcho (TEXT)
            }
        }
    }
}

