@Library ("tci-library") _

pipeline {
    agent { label 'tci-jnlp-node' }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
    }
    stages {
        stage("test") {
            steps {
                script {
                    echo "TODO: find a way to test the 'env' steps"
                }
            }
        }
    }
}
