@Library ("tci-library") _

import tci.multiJob.phase

pipeline {
    agent { label 'tci-jnlp-node' }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
    }
    stages {
        stage("test") {
            steps {
                script {
                    def job_names=['test-tciGeneral',
                                   "test-tciBuildUser",
                                   "test-tciJobs",
                                   "test-tciGit",
                                   "test-tciEnv",
                                   "test-tciNotifications",
                                   "test-tciPython",
                                   "test-tciTemplatePipeline",
                                   "test-tciLogger",
                                   "test-tciSecurity",
                                   "test-mavenCIJob"]
                    def testPhase = new phase(this)

                    for (item in job_names) {
                        String currentJobName = item
                        testPhase.addJob(jobName: currentJobName)
                    }

                    testPhase.run()
                }
            }
        }
    }
}
