@Library ("tci-library") _

import tci.multiJob.phase
import tci.multiJob.stepsBlock

pipeline {
    agent { label 'tci-jnlp-node' }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
    }
    stages {
        stage("test") {
            steps {
                script {
                    def testPhase = new phase(this)
                    testPhase.addJob(jobName: 'test-tciGit')
                    testPhase.addJob(jobName: 'test-tciGit')
                    testPhase.run()
                }
            }
        }
    }
}
