@Library ("tci-library") _

import tci.pipeline.parallelPhase

pipeline {
    agent { label 'tci-jnlp-node' }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
        ansiColor('xterm')
        skipDefaultCheckout()
    }
    stages {
        stage("test") {
            steps {
                script {
                    def job_names=['test-tciGeneral',
                                   "test-tciBuildUser",
                                   "test-tciJobs",
                                   "test-tciGit",
                                   "test-tciEnv",
                                   "test-tciNotifications",
                                   "test-tciPython",
                                   "test-tciTemplatePipeline",
                                   "test-tciLogger",
                                   "test-tciParallelPhase",
//                                   "test-mavenCIJob",
                                   "test-tciSecurity"]
                    def testPhase = new parallelPhase(this, "TCI overall tests", false)

                    for (item in job_names) {
                        testPhase.addSubJob(job:item)
                    }

                    testPhase.run()
                }
            }
        }
    }
}
