@Library ("tci-library") _

pipeline {
    agent { label 'tci-jnlp-node' }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
    }
    stages {
        stage("TCI overall") {
            steps {
                script {
                    def job_names=['test-tciGeneral',
                                   "test-tciBuildUser",
                                   "test-tciJobs",
                                   "test-tciGit",
                                   "test-tciEnv",
                                   "test-tciNotifications",
                                   "test-tciPython",
                                   "test-tciTemplatePipeline",
                                   "test-tciLogger",
                                   "test-tciSecurity",
                                   "test-mavenCIJob"]
                    def jobs = [:]

                    job_names.each{ jobs[it] = {
                            stage(it) {
                                build job: it, wait: true
                            }
                        }
                    }
                    parallel jobs
                }
            }
        }
    }
}
